name: TestUser

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: List project structure
        run: ls -R

      - name: Compile main and test classes
        run: |
          mkdir -p out
          javac -d out -cp "libs/junit-platform-console-standalone-1.6.0.jar" \
            src/main/java/com/mycompany/st10447986_prog5121_poe/Message.java \
            src/test/java/com/mycompany/st10447986_prog5121_poe/MessageTest.java

      - name: Run tests
        run: |
          java -jar libs/junit-platform-console-standalone-1.6.0.jar \
            --class-path out \
            --scan-class-path
