# Name of the workflow shown in GitHub Actions UI
name: TestUser

# When the workflow should run
on:
  push:
    branches: [ main ]           # Trigger on push to the main branch
  pull_request:
    branches: [ main ]           # Trigger on pull request targeting main
  workflow_dispatch:             # Allow manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest       # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository's code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java (JDK 17 in this case)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'        # AdoptOpenJDK distribution
          java-version: '17'            # Java version required

      # Step 3: Download necessary libraries (JUnit & JSON.simple)
      - name: Download dependencies (JUnit 4 and JSON.simple)
        run: |
          mkdir -p libs
          # JUnit core
          curl -L -o libs/junit-4.13.2.jar https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
          # Hamcrest for assertions (JUnit dependency)
          curl -L -o libs/hamcrest-core-1.3.jar https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
          # JSON.simple library
          curl -L -o libs/json-simple-1.1.1.jar https://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar

      # Step 4: Compile main and test classes
      - name: Compile Java source and test classes
        run: |
          mkdir -p out
          # Compile both source and test files with required libraries
          javac -cp "libs/*" -d out \
            src/main/java/com/mycompany/st10447986_prog5121_poe/Message.java \
            src/test/java/com/mycompany/st10447986_prog5121_poe/MessageTest.java

      # Step 5: Run the tests using JUnit 4
      - name: Run tests with JUnit
        run: |
          # Run the test class using JUnit runner and include all dependencies
          java -cp "out:libs/*" org.junit.runner.JUnitCore com.mycompany.st10447986_prog5121_poe.MessageTest
